language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
  - sudo apt-get install python-m2crypto
install:
  - pip install -r requirements.txt --use-mirrors
script: python test_sulu.py
